name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 12
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm run install-all
      - run: npm run build
      - run: git add . && git commit -am 'build' && git push
