name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci
      - run: npm run build
      - run: |
          git config --global user.name "zacanger"
          git config --global user.email "zac@zacanger.com"
          git add . && git commit -m 'build' --allow-empty && git push origin master
